### ISSUE TITLE
주간 차트 날짜 관련 논의하고 싶은 게 있습니다.

### ISSUE THREAD

**Issue by Seohyun-Roh** [POB-Frontend-4th-6team/WOB-madup-assignment-Bteam#26]
만약 4/8(금) \~ 4/13(수) 까지 날짜를 선택하고 주간 차트를 클릭할 경우, 4월 둘째 주와 셋째 주의 결과값이 보여질텐데 이 때 각각의 계산을 어떻게 해야 할 지 고민입니다.

월\~일요일을 한 주로 친다면 선택한 날짜 중 4월 둘째 주는 8, 9, 10으로 3일 밖에 없는데 이럴 경우 3일의 평균을 4월 둘째주의 값으로 해야 할까요? 아니면 그 주의 첫 요일인 4/4(월)부터 4~10(일)까지로 해야할까요?

**Comment by hyebin829** [comment]
lever 홈페이지에서 같은 날짜를 선택하면 4월 4일~4월 11일로 나오는게 이렇게 하는게 어떨까요?
이렇게도 계산이 가능한가요??

**Comment by in3166** [comment]
데이터가 없는건 어쩔수 없으니 3일의 평균을 줘도 괜찮지 않을까 싶습니다..

**Comment by Seohyun-Roh** [comment]
lever 홈페이지 들어가서 날짜 이것저것 바꿔서 보고 있는데 하면 할수록 헷갈리네요.. 
4월 한 달을 선택할 경우 보통 주간 차트라면 4월 1주, 2주, 3주 이런 식으로 나와야 할 것 같은데 lever 홈페이지에서는 3월 28일이랑 4월 25일 이렇게 두 개만 비교하고 있어요.. 🥲

**Comment by sgjibecon** [comment]
제 생각엔 lever 홈페이지 주간 통계 로직자체가 월요일을 기준으로 하는것같습니다 
예를들어 4월 한달 선택이면  3월 28일이 월요일이니 3월 28일 ~ 마지막째주 월요일까지 보여지는거죠 4/8(금) ~ 4/13(수) 도 마찬가지로 
4월 첫번째주 월요일(4일) ~ 4월 둘째주 월요일(11일) 까지 나오네요

**Comment by Seohyun-Roh** [comment]
너무 헷갈리네요ㅠㅠㅜ 일단 처음에 입력 받은 날짜대로만 한번 해보고 후에 없는 값까지 고려해보도록 하겠습니다..
의견 더 있으시면 남겨주세요
